feat: add gcp aliases

diff --git a/shells/gcp b/shells/gcp
--- a/shells/gcp
+++ b/shells/gcp
@@ -3,3 +3,90 @@
 alias eag="$EDITOR ~/dotfiles/shells/gcp; source ~/dotfiles/shells/gcp"
 
 alias gpl="gcloud projects list"
+
+alias gbl="gcloud builds list --project corp-admin --ongoing"
+alias gblog="gcloud builds log --project corp-admin"
+
+function gcp-list-ip() {
+        for p in $(gcloud projects list --format 'table[no-heading](projectId)'); do
+                gcloud services list --project $p | grep compute.googleapis.com >/dev/null 2>&1
+                if [[ $? == 0 ]]; then
+                        result=$(gcloud compute addresses list --project $p 2>&1)
+                        if [[ ${result} != "Listed 0 items." ]]; then
+                                echo "***** ${p} *****"
+                                echo ${result}
+                        fi
+                fi
+        done
+}
+
+function gke-resolve-project() {
+        local env=$1
+        if [[ ${env} == "" ]]; then
+                echo "Argument Cluster GKE necessaire"
+                return 1
+        fi
+
+        case "$1" in
+        'prod01')
+                echo "corp-prod-gkeinfra"
+                ;;
+        'prod02')
+                echo "corp-prod-gke"
+                ;;
+        'devl01')
+                echo "corp-devl-gke"
+                ;;
+        'prod1')
+                echo "prod-gke-230115"
+                ;;
+        'dev1')
+                echo "devl-gke-230115"
+                ;;
+        'labo1')
+                echo "labo-gke-237917"
+                ;;
+        *)
+                return 1
+                ;;
+        esac
+}
+
+function gke-info() {
+        local PROJECT
+        local cluster
+        cluster=$1
+
+        PROJECT=$(gke-resolve-project ${cluster})
+        if [[ $? != 0 ]]; then
+                echo >&2 "Argument invalide"
+                return 1
+        fi
+
+        gcloud container clusters list --project $PROJECT --format="table[box,title='Master ($PROJECT)'](NAME, MASTER_VERSION, MASTER_IP, NUM_NODES, STATUS)"
+        if [[ ${env} == "prod01" ]] || [[ ${env} == "prod02" ]] || [[ ${env} == "devl01" ]]; then
+                gcloud container node-pools list --cluster ${cluster} --project $PROJECT --zone "northamerica-northeast1-a" --format="table[box,title='Nodepools ($1)'](NAME, MACHINE_TYPE, DISK_SIZE_GB, NODE_VERSION)"
+        else
+                gcloud container node-pools list --cluster ${cluster} --project $PROJECT --region "northamerica-northeast1" --format="table[box,title='Nodepools ($1)'](NAME, MACHINE_TYPE, DISK_SIZE_GB, NODE_VERSION)"
+        fi
+}
+
+function gke-nodepool-info() {
+        local PROJECT
+        local cluster
+
+        cluster=$1
+        shift
+
+        PROJECT=$(gke-resolve-project ${cluster})
+        if [[ $? != 0 ]]; then
+                echo >&2 "Argument invalide"
+                return 1
+        fi
+
+        if [[ ${env} == "prod01" ]] || [[ ${env} == "prod02" ]] || [[ ${env} == "devl01" ]]; then
+                gcloud container node-pools describe --cluster ${cluster} --project $PROJECT --zone "northamerica-northeast1-a" "$@"
+        else
+                gcloud container node-pools describe --cluster ${cluster} --project $PROJECT --region "northamerica-northeast1" "$@"
+        fi
+}
